[package]
name = "cosmic-ext-applet-external-monitor-brightness"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
repository = "https://github.com/cosmic-utils/cosmic-ext-applet-external-monitor-brightness"

[dependencies]
ddc-hi = "0.4.1"
i18n-embed = { version = "0.16.0", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.10"
rust-embed = { version = "8.11.0", features = ["debug-embed"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3.22", features = ["fmt", "env-filter"] }
tracing-journald = "0.3"
tokio = { version = "1.52.1", features = ["sync"] }
serde = { version = "1.0.228", features = ["derive"] }
dirs = "6"
anyhow = "1.0.102"
zbus = { version = "5.14", default-features = false, features = ["tokio", "blocking-api"] }

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
rev = "511384f6206527cf87369da67a9164831afbabef"
default-features = false
features = ["applet", "tokio", "wayland"]

# [patch."https://github.com/smithay/client-toolkit.git"]
# sctk = { package = "smithay-client-toolkit", version = "=0.19.2" }

# [patch."https://github.com/pop-os/libcosmic"]
# libcosmic = { path = "../libcosmic"}
